### ISSUE TITLE
HTTP Response after receipt of an Envelope with an empty payload

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-central#164]
The 1.1 spec is silent on how an endpoint should respond if it receives an `Envelope` with an empty `data` payload (e.g., "data" : []).  Does an empty payload render the `Envelope` "malformed" (assuming of course the other properties have been properly specified)?  The scenario described below suggests that only in cases of missing properties is an `Envelope` to be considered malformed. 

> If the Sensor sends a malformed Caliper Envelope (it does not contain sensor, sendTime, dataVersion and data properties of the required form), the Endpoint SHOULD reply with a 400 Bad Request response. Note that the Endpoint SHOULD NOT send a 400 Bad Request response if the Envelope contains a dataVersion value that the Endpoint cannot support; in this case, the Endpoint SHOULD send a 422 Unprocessable Entity response instead. [1]

Question: How should an endpoint respond if it receives an `Envelope` with an empty payload (note that an empty array is not invalid JSON)?

If Envelope with an empty payload is to be rejected by an endpoint, we may well need to specify more explicitly acceptable/unacceptable `Envelope` values. 

[1] https://github.com/IMSGlobal/caliper-spec/blob/master/caliper-spec.md#httpResponse

**Comment by ViktorHaag** [comment]
I'm inclined to think that envelopes with no contained values might need to be admitted by the spec as valid. We can talk about this in an upcoming meeting -- simple heartbeat sensors might well want to be sending empty payloads, conceivably?
