### ISSUE TITLE
Should Event.referrer be a list?

### ISSUE THREAD

**Issue by ViktorHaag** [IMSGlobal/caliper-central#183]
It's potentially a breaking change, but should Event.referrer be a list, so that a context chain of things could get sent with an Event?

A way to keep backwards compatibility, I suppose, would be to create a new Referrable called a "context chain" or something, whose only purpose in life would be to act as a container for other Referrables (rather like we have a DigitalResourceCollection)...

**Comment by mgylling** [comment]
Closed per WG decision on 20180626 call. Event referrer stays as a singleton for now. If a use cases emerges in the future, we'll reopen.
