### ISSUE TITLE
best practice for AssessmentItem attempts

### ISSUE THREAD

**Issue by lindafengsf** [IMSGlobal/caliper-central#186]
Hi - a few questions have come up recently that I'm hoping to get clarification/guidance around:

1. When capturing scores for Assessment Item attempts, is GradeEvent the appropriate event to be used?  
2. Sometimes an assessment attempt can span multiple sessions.  What is the best way to capture multiple records to indicate someone is resuming a session to continue working on an assessment?
3. In the case where multiple attempts are allowed per question, can incomplete attempts result in a completed AssessmentItem event?

Thanks!

**Comment by joshuamcghee** [comment]
Closing this issue as the implementation guide updates will be managed in #224
