### ISSUE TITLE
How much to include in Caliper events?

### ISSUE THREAD

**Issue by lindafengsf** [IMSGlobal/caliper-central#188]
One of the questions I'm coming across lately is how much "actual" information should be included in Caliper event?  On the one hand, if all objects are persisted and accessible via dereferenceble IRIs, why not streamline all Caliper payloads to reference ids and timestamps only?

Can we perhaps come up with a some guidelines might be useful to help application designers?  Something like this maybe:

1. Data generated by the app **which would otherwise be lost** (i.e. not persisted) would be a good candidate to convey in a Caliper event
2. For data which is readily accessible via dereferenceble IRI's, it is ok to include just the IRI's
3. If there are cases where downstream processes would need quick access to the actual generated data, it is ok to include data values as well [ANY BEST PRACTICES HERE WOULD BE APPRECIATED]

Also - it seems to me that these rules would be good to document as well:
1) **only emit what you generate**: in other words, if your application has to do any extra work to retrieve related information, it's not recommended to include it in the event payload.
2) any identifiers generated by your app should be represented as first class properties in the Caliper event; however any identifiers which were passed into your application (say as LTI launch parameters) should be included as federatedSession properties

Any other thoughts here welcome -

**Comment by joshuamcghee** [comment]
this issue was resolved with https://github.com/IMSGlobal/caliper-spec/pull/415
