### ISSUE TITLE
How to represent a grade change event?

### ISSUE THREAD

**Issue by lindafengsf** [IMSGlobal/caliper-central#189]
Currently, the GradeEvent has an action of Graded and the generated property for the Score.  However, what would be the best way to represent a subsequent change to the grade?  

If we use the same GradeEvent, is it sufficient to record successive events with the same Graded action, just with the latest event recording the new score?  Or is it more appropriate to record it as a separate action and transmit both "old" and "new" score objects?

**Comment by sent1nel** [comment]
Late to the party here. Our implementation does not specify, semantically, anything different for new/updated grades. We do include attempt information, but if this is an updated grade for the same assessment or learning material, this is not actually changed. We simply assume that newer grade events for the same activity supersede those of previous activities. You may be onto something here with this idea of an Updated action; this way, if there are grade Updates but no original Graded events, a research could recognize that something is off?

**Comment by joshuamcghee** [comment]
closing this issue as the implementation guide updates will be handled in #224
