### ISSUE TITLE
AssignableEvent in cert suite requires Submitted vs Completed

### ISSUE THREAD

**Issue by dknight-bb** [IMSGlobal/caliper-central#196]
The cert suite for 1.1 specifies Submitted as a required action and Completed as recommended. However, there is no discussion in the spec about how to understand the difference between those two. 

Additionally, in 1.0, Completed was required not recommended. 

Was there a particular reason for this change? How should "Submitted" vs "Completed" for an Assignable event be understood?

**Comment by arwhyte** [comment]
See https://github.com/IMSGlobal/caliper-spec/blob/master/caliper-spec.md#actions

Specifically:

Completed (http://purl.imsglobal.org/caliper/actions/Completed): Come or bring to a finish or an end.
Submitted (http://purl.imsglobal.org/caliper/actions/Submitted): Hand over formally.

Submitted is the act of formally handing over an assignable for evaluation.  It infers a status of completed although an actor could submit an assignable that is in an incomplete state.  

Completed indicates that an actor as finished an assignable.  It makes no claims nor should it be inferred that the completed item has been submitted for evaluation.

**Comment by dknight-bb** [comment]
>  It makes no claims nor should it be inferred that the completed item has been submitted for evaluation

That seems at best an inference from a negative. In other words, that Submitted indicates "hand over formally" is clear from the definition, but that "Completed" excludes "submitted for evaluation" is not apparent. I.e, it is quite reasonable to assume "complete" or "bring to an end" means there is no further action for the student. 

Even that alone doesn't specify why one over the other is considered "required" by the certification suite.

**Comment by arwhyte** [comment]
Per Caliper 1.1 the "bookend" actions are `Started` and `Submitted`.   All other actions are considered as occurring between `Started` and `Submitted`.  Happy to clarify this distinction in the body of the spec itself.

**Comment by dknight-bb** [comment]
Per Caliper 1.1? I find know mention of anything remotely resembling that "bookending" in the spec. It would be more than a clarification; it would be a material change. 

As I previously pointed out, there is nothing in the definition of "Completed" ("Come or bring to a finish or an end.") which excludes ipso facto "Submitted" ("hand over formally"). In fact, Started and Completed are logical opposite ends (i.e. the opposite of starting is ending).

**Comment by ojurosevic** [comment]
**Completed** ( by Merriam Webster)

implies the removal of all deficiencies or a successful finishing of what has been undertaken

**Completed** (by Dictionary.com)

to make whole or entire 

 e.g I need to answer to more questions to complete the quiz 

_Complete_ implies that a certain entity has all its parts, fully developed or perfected, and may apply to a process or purpose carried to fulfillment


Assessment entity with action status COMPLETED  implies that the entity has all its parts fully developed or answered or perfected and is ready to be carried thru the release/publication or submission process.

Good synonym is  _to be finished_ 


Assessment entity with action status SUBMITTED implies that the entity has been presented for review or grading .

Good synonym is _to  be sent_

**Use Cases :** 
1. a student completes ( or finishes) an assessment and then submits it for grading right away . 
2. a student completes an assessment to her best knowledge but doesn’t submit it until its deadline 


_Implementation dilemma ( Canvas by Instructure Use Case) :_ 

Anytime we use _Completed_ status we make an assumption that an end user finished her assessment tasks and  is satisfied with the final result ( there are no missing tasks left). There may be solutions that allow end user to mark an assessment as _Completed_ ( a specific feature of the solution e.g a button or option on the screen) but majority of web solutions will not have this option,  instead they will only allow their end user to either SAVE assessment results as a Draft or will automatically save the assessment items that were already answered. In both cases the Entity that gets generated as a result of the SAVE action is _Attempt_ with action set to _Created_    

When an end user is ready to submit the results she uses Submit option to send the finished assessment tasks for review/grading. As a result of this action a new message is issued with the entity type : _Attempt_ action set to _Submitted_ 

In the event when an end user modifies a previously generated _Attempt_ before submitting it, there will be a new message with the action set to Modified issued prior to the  message with action set to _Submitted_ .


My suggestion is to use Completed status only in the solutions that specifically support this option and avoid re-purposing other statuses to fit the definition of Completed. 


Let me know if the definitions of Submitted and Completed suffice and we could include them to the Caliper Vocabulary and Implementation guide.

**Comment by dknight-bb** [comment]
Blackboard has a similar situation re: Completed vs Submitted. There's no logical place in the workflow for Completed to be sent without Submission occurring. 

As an aside, how do "ended" and "completed" differ? Both seem opposed to Started. Is a process ended but an object completed? 

> Let me know if the definitions of Submitted and Completed suffice and we could include them to the Caliper Vocabulary and Implementation guide.

I'm not sure which definitions you are actually proposing. The key issue is (although, I don't really have a horse in this race for much longer) that complete/to be finished can refer either to the assement as a (virtual) object or as the process of taking the assessment, thus "finished" can refer to either the state of where no further work can be done with answering it ( no submitted) or the state where no further actions at all can be done (i.e. including submitted). Whatever definitions are proposed that distinction needs to be clear.

**Comment by ojurosevic** [comment]
@dknight-bb I'm working in context of Caliper v1.1  where Completed action is currently only available for AssignmentItemEvent and AssignableEvent with Attempt and Response as the main entities . I don't believe there are any questions around the definition of Submitted, all I am proposing is to elaborate on it and add an example such as :" Assessment entity with action status SUBMITTED implies that the entity has been presented for review or grading".  

The open question is whether Completed action is  a meaningfully action for the Attempt and Response entities and whether we have a clear definition of Completed in Caliper dictionary.

 The definition I propose is : 

"_Complete_ implies that a certain entity has all its parts, fully developed or perfected, and may apply to a process or purpose carried to fulfillment
_Example:_ 
Assessment entity with action status COMPLETED implies that the entity has all its parts fully developed or answered or perfected and is ready to be carried thru the release/publication or submission process."

Use case for AssessmentItem Event with Attempt action set to Completed  : 

 - a student answered an assessment question and marked it as Completed . In this case the system offers some type of feature that allows a user to mark an item as completed. If there is no such feature the workflow state will change from  for an example Started to Submitted omitting Completed state all together. 

Use case for AssignableEvent with Attempt action set to Completed: 

- an assignment has a set of rues a user has to meet to complete the assignment, a web solution has a feature that allows a user to mark the assignment as completed after the conditions are satisfied. The assignment could be submitted by the user for review after it was marked  as "completed" or the system could auto-submit it as soon as the assignment workflow state is set to completed. Regardless of the case : the system has to have an explicit state and conditions to mark an attempt for a specific assignable resource as completed.

**Comment by dknight-bb** [comment]
In Caliper 1.1, Completed is also available on the Assignable Metric Profile. This is in fact the reason cited by Anthony why the cert suite was changed between 1.0 and 1.1 to expect Submitted instead of Completed for AssessmentEvents.

The problem isn't with the definition itself but clarifying the definition of Completed to determine how Submitted relates to it; that was the entire contention above between Anthony and myself, namely a) that there was a change in the "required" verbs and b) he asserted that completed could not include submission whereas I argued that the definition given did not clarify that. 

Note also that in the current version of the 1.1 spec, there are no definitions of actions per Event/Metric profile, no examples, no specific use cases. There is only a link from the Event to the Appendix where there is a linked gloss (cited above by Anthony). It *might* make sense in future versions of the spec or in ancillary documentation to outline specific use cases envisioned by various actions for particular metric profiles, but that's not currently what's in the 1.1 spec.

I agree that in practice there is no real distinct state between Completed and Submitted with the caveat that something being Submitted but not Completed is at least theoretically possible (e.g. an automatic submission when a due date arrives), but that seems more likely to be modeled with an isComplete flag on an event.

**Comment by ojurosevic** [comment]
@dknight-bb I think the new Caliper implementation guide : https://github.com/IMSGlobal/caliper-impl-guide/blob/master/caliper-impl-guide.md is the write place to have those two action types defined with use cases as a ref. 

@dknight-bb you mentioned you are not going to be a part of Caliper workgroup soon ( I don't really have a horse in this race for much longer ) are you changing roles? I am new to Caliper implementation at Canvas, was wondering if I could chat with you about some lessons learned when it comes to implementing Caliper messages.

**Comment by dknight-bb** [comment]
I would agree that the implementation guide is the correct place to elaborate on specific understanding of Actions within specific Metric Profiles, but I also think the definition included in Appendix A of the Spec itself needs some modification to reduce the above ambiguity.

@ojurosevic Yes, I will no longer be working with Caliper after this week. I'm happy to have some conversation and attempt to answer any questions.

**Comment by ojurosevic** [comment]
@dknight-bb do you have an email I can use to reach out ?

**Comment by dknight-bb** [comment]
Yes, I'll email you.

**Comment by joshuamcghee** [comment]
Per @ojurosevic this issue was resolved with Submitted being the required action for certification now.  She defined actions and added them with use cases to the implementation guide.
