### ISSUE TITLE
AggregateMeasureCollection has little value; we should remove it

### ISSUE THREAD

**Issue by ViktorHaag** [IMSGlobal/caliper-central#214]
In the ToolUse profile (for progress), the AggregateMeasureCollection entity provides little value. We should remove it and simply have a list of AggregateMeasures in the hosting event, instead of the collection entity.

**Comment by dccarroll** [comment]
This sounds great to me!

**Comment by arwhyte** [comment]
My suggestion in slack was pointing to the remove any reference to a collection of measures.  One `AggregateMeasure` per `ToolUseEvent` only.  If you want to send additional measures mint additional events.

**Comment by dccarroll** [comment]
@arwhyte - That wouldn't work well for the most common use case we see in the wild at Clever - applications wanting to send one event that includes both time on task (metric=minutes) and curriculum progress (metric=lessons passed, etc).

Is there any reason @ViktorHaag's suggestion of having Generated accept a list of AggregateMeasures wouldn't work?

**Comment by ViktorHaag** [comment]
The reason, which Anthony reminds me of, is that `Event.generated` is a single entity, and not a list. I'm inclined at this point to side with Anthony, and say that if you have multiple measures, you send multiple events, and we kick the notion of a generic `Collection` down the road.

**Comment by arwhyte** [comment]
Closing this issue given that the Caliper Technical Working Group has agreed to retain `AggregateMeasureCollection` as well as add a `Collection` entity which will serve as the super type of `AggregateMeasureCollection`.
