### ISSUE TITLE
group all Navigation and Viewed events into Navigation Profile

### ISSUE THREAD

**Issue by ojurosevic** [IMSGlobal/caliper-central#219]
I am requesting to group all  `navigate to`  events into Navigation or some type of Asset Accessed profile . I don’t think any provider who implemented Caliper would mind it , and it will make Instructure implementation way cleaner therefore less issues for our customers when it comes to consuming the events. The new change in Caliper 1.2 requires sensor to specify profile  in the event json, this will force Instructure to hardcode every single asset to a specific profile  when it comes to `NavigatedTo` and `Viewed` events
At the moment all `navigated to` and `viewed`  events are under several profiles , depending on the asset end user navigates to.In our code base we literally have to dissect every single  `asset_accessed` event, extract the asset and then hardcode the asset type to specific Caliper profile.

**Comment by ViktorHaag** [comment]
I have sympathy for this situation, and I don't mind the proposal. However, this _will_ mean that rules about "what to do" with Navigation and View events will not be exposed to individual metric profiles, and the only rules that they'll be able to follow will be the ones defined in this "Asset Accessed" profile (or whatever we might choose to call it).

One of the guiding principles in Caliper's original design was that the flexibility of being able to use 
and re-use vocabulary, events, and entities across different profiles, and then expect slightly different uses for them, was something we valued.

We should consider that when deliberating on this proposal as well.

**Comment by ojurosevic** [comment]
I spoke with Kara Armstrong about it as well and  are planning on speaking to a few other customers, it does sound like the schools Kara spoke with requested the profiles to stay as is for the `NavigatedTo` and `Viewed` events , in their use cases it brings more value to tie profile to accessed asset type vs the action performed. As soon as I complete my customer interviews I'll resurface this issue, for now I am going to close it.
