### ISSUE TITLE
Add Best Practice Guide to Caliper Central

### ISSUE THREAD

**Issue by joshuamcghee** [IMSGlobal/caliper-central#221]
The best practice guide, located [here](https://www.imsglobal.org/caliper/caliperv1p0/ims-caliper-analytics-best-practice-guide) is not in the caliper central repo.  This issue is being raised to get it added to the doc set in caliper central.

**Comment by arwhyte** [comment]
This issue can be closed.  The implementation guide is the best practices guide.
