### ISSUE TITLE
Add `LtiDeploymentId` as an `identifierType` to `otherIdentifiers`

### ISSUE THREAD

**Issue by bracken** [IMSGlobal/caliper-central#225]
This is a recommended addition to the recent feature discussed in issue #204 
For LTI 1.3, the best way to identify the tool deployment is with the deployment ID. Since it may be common for Caliper consumers to want to tie their events to an LTI configuration in an LMS, for example, we think it might be appropriate to have an `identifierType` specifically for this called something like `LtiDeploymentId`

An example of what that'd look:
```json
  "otherIdentifiers": [
    {
      "type": "SystemIdentifier",
      "identifier": "example.edu:SI182-F16",
      "identifierType": "LtiDeploymentId"
    }
  ],
```

**Comment by ViktorHaag** [comment]
Going to close -- this is already addressed with [merged context PR #93]( https://github.com/IMSGlobal/caliper-contexts/pull/93) and [spec PR #405](https://github.com/IMSGlobal/caliper-spec/pull/405).
