### ISSUE TITLE
Move caliper-contexts develop branch to caliper-spec develop branch

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-central#231]
Do the following:

1.  Move the caliper-contexts develop branch to caliper-spec develop.  Place the JSON-LD contexts into contexts/ directory.  Retain history.
2.  Delete caliper-contexts develop branch and then archive the caliper-contexts repo.

Do this for 1.2.

**Comment by bracken** [comment]
the repo is archived now too.
