### ISSUE TITLE
Add bibliographic support entities for use with sensor API DESCRIBE method

### ISSUE THREAD

**Issue by fullersr** [IMSGlobal/caliper-central#59]
We should allow the ability to relate the DigitalResource that is referenced in the reading and other sensors to a bibliographic entry.  While this could be done within each relevant sensor it is possibly best done in the DESCRIBE method.  Doing so would allow the resource to be fully described once per user session.

A promising ontology for bibliographic description is FABIO (not the 1980's long haired guy) http://www.sparontologies.net/ontologies/fabio/source.html.

**Comment by mgylling** [comment]
Decision to close on WG call 20180703. Bibliographic information is static and can be fetched asynchronously/after the fact for those that need/want it.
