### ISSUE TITLE
Consider changing Event.generated from object to array

### ISSUE THREAD

**Issue by arwhyte** [IMSGlobal/caliper-central#80]
This is a placeholder for further discussion regarding the wisdom of considering a change in the data type of `Event.generated` from an object to an array. The idea here is to accommodate an outcomes scenario in which a result (in a general sense) might include not simply the recording of a score but also the attainment of some level of mastery with respect to a competency or the issuance of a micro-credential, etc.  Now it remains true that a platform could emit more than one event (e.g., Event1: `Agent` graded `Attempt` and generated a `Result`, Event2: `Person` demonstrated Evidence or earned/is awarded a Competency . . .).  Now `Result` could be provisioned with an optional object property that references a Competency earned or some other evidence indicator.  That might be the way to proceed (e.g., issue more than one `Event`) since it requires no change to the `Event` model's `generated` type.  But an efficiency gain might be had by converting `Event.generated` to an array as in:

```
{
    "generated": [
        {
            "id": "http://example.org/results/123",
            "type": "Result",
            "score": "95"
            . . .
        },
        {
            "id": "http://example.org/competencies/1",
            "type": "Competency",
            "masteryLevel": "Expert"
            . . .
        }
    ]
}
```

**Comment by mgylling** [comment]
Closed as per WG decision on 20180626 call.
